### ISSUE TITLE
Error when launching analysis in SonarQube

### ISSUE THREAD

**Issue by chortels** [fortitudetec/sonar-ruby-plugin#9]
Hi,

I've  followed the indicated steps to run a Ruby analysis in SonarQube 6.7: 

- Run rubocop making sure that the json results file is created with 'rubocop --format=json --out=rubocop-result.json', and I see that a rubocop-result.json file is created. 

- Run your specs (make sure that your sonarqube config points to the right coverage directory ). I haven't been able to reproduce this step, because when executing 'bundle exec rspec spec' the output is "Could not locate Gemfile or .bundle/ directory". 

- My sonar-project.properties is configured: 

`sonar.projectKey=ruby:my-application
sonar.projectName=Ruby-My_application
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts

sonar.ruby.file.suffixes=rb,ruby
sonar.ruby.coverage.reportPath=coverage/.resultset.json
sonar.ruby.coverage.framework=RSpec
sonar.ruby.rubocopConfig=.rubocop.yml
sonar.ruby.rubocop=C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.58.2/exe/rucobop.exe
sonar.ruby.rubocop.reportPath=C:/Users/my_user/Desktop/skeleton/rubocop-result.json
sonar.ruby.rubocop.filePath=.`

And, when launching `sonar-scanner`, this error appears:

`13:17:37.813 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovParser.parse(SimpleCovParser.java:50)
        at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovSensor.execute(SimpleCovSensor.java:31)
        at com.fortitudetec.sonar.plugins.ruby.metrics.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:28)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
13:17:37.858 DEBUG: Execution getVersion
13:17:37.860 DEBUG: Execution stop`

Any idea about what is happenning?

Regards!

**Comment by chrisrohr** [comment]
Hi, were you running this on your own project or with the test integration project that is in this repo?

The error looks like it has to do with not being able to find the coverage results.  Which would make sense since you mentioned you had issues running the specs.

**Comment by chortels** [comment]
Hi @chrisrohr , 

With another project I've been able to obtain bugs, code smells and vulnerabilities in SonarQube, through the rubocop-result.json that is generated. However, I've seen that, if coverage folder, which includes .resultset.json, is sent to SonarQube, this tool returns a null pointer exception.

`ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovParser.parse(SimpleCovParser.java:50)
        at com.fortitudetec.sonar.plugins.ruby.simplecov.SimpleCovSensor.execute(SimpleCovSensor.java:31)
        at com.fortitudetec.sonar.plugins.ruby.metrics.CombinedCoverageSensor.execute(CombinedCoverageSensor.java:28)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

And if I remove this coverage folder and launch the SonarQube analysis, the execution is succesful (but, obviously, I don't see coverage parameters). 

Regards

**Comment by chrisrohr** [comment]
Are you using RSpec or minitest or some other framework?

The error is happening here:

```
Map<String, List<Integer>> coverageByFile = results.get(testFramework).get("coverage");
```

I'm guessing either you aren't using RSpec (your properties file indicates you are) or the results.json file doesn't have the RSpec -> coverage elements

**Comment by chortels** [comment]
Hi @chrisrohr , 

I think this is caused because when i run `bundle exec rspec spec` on the integration/todo project, bundle returns '0 examples, 0 failures'. Is this possible? When launching `bundle exec rspec spec`, Bundle looks for the spec directory, but it doesn't appear on the integration/todo project. Is this right?

Thank you for your help. Regards.

**Comment by chrisrohr** [comment]
Ah yes, the integration todo app is using minitest not rspec. Try `bin/rails test`.  This is the default testing framework with rails and I didn’t change it for the integration app. In `sonar-project.properties` it should say that the framework is MiniTest.

Hope this helps

**Comment by chortels** [comment]
Hi @chrisrohr . I changed the value of sonar.ruby.coverage.framework to MiniTest, but the output of the analysis remains the same. That's the reason why I've tried with a simpler project, the one that is in https://www.cakesolutions.net/teamblogs/brief-introduction-to-rspec-and-simplecov-for-ruby. 

My structure is the following: 

**-spec
-spec/spec_helper.rb
-spec/string_ops_spec.rb
-Gemfile
-sonar-project.properties
-string_ops.rb**

And this is my sonar-project.properties:

`sonar.projectKey=fortititudetec:todo
sonar.projectName=ToDo Application
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=spec
sonar.test.inclusions=**/*.spec.ts

sonar.ruby.file.suffixes=rb,ruby
sonar.ruby.coverage.reportPath=coverage/.resultset.json
sonar.ruby.coverage.framework=RSpec
sonar.ruby.rubocopConfig=.rubocop.yml
sonar.ruby.rubocop=/usr/bin/rubocop
sonar.ruby.rubocop.reportPath=rubocop-result.json
sonar.ruby.rubocop.filePath=.`

Before executing sonar-scanner, `bundle exec rspec spec ` returns this: 

**Coverage report generated for RSpec to C:/Users/chortels/Desktop/string/coverage. 6 / 7 LOC (85.71%) covered.**

However, when I see the quality analysis in SonarQube, the coverage is 0%. 

Regards

**Comment by chrisrohr** [comment]
Hmm, would you mind attaching the output in the `coverage/.resultset.json` file here?  I'm wondering if I have a parsing issue.  Also what version of simplecov are you using?

Thanks

**Comment by chrisrohr** [comment]
@chortels Were you able to get this working?  Also, just an FYI, that as of SonarQube 7.4, they have built their own Ruby analyzer plugin, so this plugin is deprecated.

**Comment by Tusabras** [comment]
also be careful there is a typo on sonar.ruby.coverage.reportPath should be sonar.ruby.coverage.reportPaths
